In [25]:
import pandas as pd

In [85]:
df = pd.read_csv("../ai_skepticism_dataset.csv")
df

,ai_model_name,query_category,ai_confidence_percentage,response_character_count,has_cited_sources,contains_hedging_words,includes_disclaimer,answer_detail_level,respondent_age_bracket,education_level,...,urgency_level,belief_alignment_status,subject_matter_expertise,trust_score_out_of_10,performed_fact_check,fact_check_method_used,verification_duration_mins,answer_accuracy_percentage,trust_calibration_valid,user_skepticism_category
0,Claude,math_calculation,93.23,527,True,False,False,Moderate,45-54,Bachelors,...,Low,False,False,10.0,True,Google Search,10.7,80.15,True,Moderate Trust
1,Llama,recipe_cooking,84.47,581,False,False,False,Specific,55-64,PhD,...,NaN,False,True,7.9,True,Asked Expert,44.3,92.33,True,Skeptical
2,Claude,general_knowledge,69.82,484,True,True,False,Very Specific,35-44,High School,...,NaN,True,False,8.6,True,Consulted Documentation,37.5,67.32,True,Moderate Trust
3,Claude,creative_writing,79.61,73,True,True,False,Specific,45-54,Professional,...,NaN,NaN,False,8.9,True,Checked Official Source,22.7,73.12,True,Moderate Trust
4,Claude,creative_writing,67.71,146,False,True,False,Vague,55-64,Masters,...,NaN,True,True,9.0,True,Academic Paper,43.7,81.05,True,Moderate Trust
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Gemini,math_calculation,94.09,661,True,True,False,Specific,35-44,Masters,...,High,True,True,10.0,False,NaN,0.0,95.33,True,Blind Trust
996,Llama,financial_advice,62.60,384,True,False,False,Vague,65+,Masters,...,High,True,False,8.4,False,NaN,0.0,68.18,True,Blind Trust
997,Claude,technical_coding,77.38,166,True,True,False,Specific,35-44,High School,...,NaN,True,True,10.0,True,Cross-referenced Multiple AIs,23.3,92.14,True,Moderate Trust
998,ChatGPT-3.5,math_calculation,98.61,71,False,True,False,Very Specific,25-34,High School,...,NaN,False,False,8.6,True,Asked Expert,43.3,100.00,True,Moderate Trust
999,Llama,opinion_based,55.61,123,True,True,False,Vague,25-34,PhD,...,Medium,False,True,5.0,True,Personal Testing,44.0,57.10,True,Skeptical

In [27]:
type_of_dataset = type(data)
type_of_dataset

pandas.core.frame.DataFrame

<h3>Data Cleaning</h3>

<h4>1️⃣ Checking & Handling Missing Values (Nulls)</h4>

<b>What are missing values?</b>
<p>Missing values occur when data is unavailable or not recorded.</p>

<p>eq --> Surveys Unanswered,Data Merge Issues</p>
<p>Many models cannot handle nulls, Biases results, Reduces prediction accuracy</p>

<h4>Check for Null Values</h4>

In [39]:
df.info() #dataset summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ai_model_name               1000 non-null   object
 1   query_category              1000 non-null   object
 2   ai_confidence_percentage    1000 non-null   float64
 3   response_character_count    1000 non-null   int64
 4   has_cited_sources           1000 non-null   bool
 5   contains_hedging_words      1000 non-null   bool
 6   includes_disclaimer         1000 non-null   bool
 7   answer_detail_level         1000 non-null   object
 8   respondent_age_bracket      1000 non-null   object
 9   education_level             1000 non-null   object
 10  digital_literacy_score      1000 non-null   object
 11  ai_familiarity_level        1000 non-null   object
 12  decision_importance         1000 non-null   object
 13  urgency_level               779 non-null    object
 14  belief_alignment_status     658 non-null    object
 15  subject_matter_expertise    1000 non-null   bool
 16  trust_score_out_of_10       1000 non-null   float64
 17  performed_fact_check        1000 non-null   bool
 18  fact_check_method_used      628 non-null    object
 19  verification_duration_mins  1000 non-null   float64
 20  answer_accuracy_percentage  1000 non-null   float64
 21  trust_calibration_valid     1000 non-null   bool
 22  user_skepticism_category    1000 non-null   object
dtypes: bool(6), float64(4), int64(1), object(12)
memory usage: 138.8+ KB

In [40]:
df.isnull().sum() # for checking if any null exists

ai_model_name                   0
query_category                  0
ai_confidence_percentage        0
response_character_count        0
has_cited_sources               0
contains_hedging_words          0
includes_disclaimer             0
answer_detail_level             0
respondent_age_bracket          0
education_level                 0
digital_literacy_score          0
ai_familiarity_level            0
decision_importance             0
urgency_level                 221
belief_alignment_status       342
subject_matter_expertise        0
trust_score_out_of_10           0
performed_fact_check            0
fact_check_method_used        372
verification_duration_mins      0
answer_accuracy_percentage      0
trust_calibration_valid         0
user_skepticism_category        0
dtype: int64

In [30]:
(df.isnull().sum()/len(df)) * 100 # important for deciding whether to drop or fill

ai_model_name                  0.0
query_category                 0.0
ai_confidence_percentage       0.0
response_character_count       0.0
has_cited_sources              0.0
contains_hedging_words         0.0
includes_disclaimer            0.0
answer_detail_level            0.0
respondent_age_bracket         0.0
education_level                0.0
digital_literacy_score         0.0
ai_familiarity_level           0.0
decision_importance            0.0
urgency_level                 22.1
belief_alignment_status       34.2
subject_matter_expertise       0.0
trust_score_out_of_10          0.0
performed_fact_check           0.0
fact_check_method_used        37.2
verification_duration_mins     0.0
answer_accuracy_percentage     0.0
trust_calibration_valid        0.0
user_skepticism_category       0.0
dtype: float64

<h4>Handling Missing Values -- 3 approaches</h4> 

<h5>Method 1 Remove Missing Data (deletion)</h5>
<p>it's mostly used when dataset is large and the column isn't important </p>

In [35]:
df.dropna(inplace=True) #drop rows with null values and inplace is used to alter the data without assigning a new variable

In [48]:
m2 = df.dropna(subset=['urgency_level']) #Drop specific column null rows
# m2.isnull().sum()

In [47]:
m3 = df.drop(columns=["belief_alignment_status"]) # Drop columns with many nulls
# m3.isnull().sum()

<h5>Method 2 — Fill Missing Values (Imputation)</h5>

<p><b>df['response_character_count'].fillna('response_character_count').mean()</b> --> filling with mean(numerical data)</p> 

<p><b>df['response_character_count'].fillna(df['response_character_count'].median(), inplace=True)</b> --> Fill with median (better if outliers exist)</p>

In [50]:
# Fill with constant value

fm3 = df.fillna(0)
# fm3.isnull().count()

fm4 = df.fillna("Unknown")
# fm4.isnull().count()

In [87]:
# Fill with mode (categorical data)
df["urgency_level"].fillna(df["urgency_level"].mode()[0])

0         Low
1      Medium
2      Medium
3      Medium
4      Medium
        ...
995      High
996      High
997    Medium
998    Medium
999    Medium
Name: urgency_level, Length: 1000, dtype: object

In [86]:
df["belief_alignment_status"].fillna(df["belief_alignment_status"].mode()[0])

C:\Users\dell\AppData\Local\Temp\ipykernel_12556\2278347340.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["belief_alignment_status"].fillna(df["belief_alignment_status"].mode()[0])

0      False
1      False
2       True
3       True
4       True
       ...
995     True
996     True
997     True
998    False
999    False
Name: belief_alignment_status, Length: 1000, dtype: bool

In [88]:
df["fact_check_method_used"].fillna(df["fact_check_method_used"].mode()[0])

0                      Google Search
1                       Asked Expert
2            Consulted Documentation
3            Checked Official Source
4                     Academic Paper
                   ...
995                  Asked Colleague
996                  Asked Colleague
997    Cross-referenced Multiple AIs
998                     Asked Expert
999                 Personal Testing
Name: fact_check_method_used, Length: 1000, dtype: object

<h4>Method 3 — Forward / Backward Fill (Time Series Data)</h4>
<p><b>df.fillna(method='ffill', inplace=True)</b># forward</p><p><b>df.fillna(method='bfill', inplace=True)</b># backward</p>d

<h4>2️⃣ Checking & Removing Duplicate Data</h4>
<b>What are duplicates?</b>
<p>Same row repeated multiple times.</p>

<h4>Check duplicates</h4>

In [90]:
df.duplicated() # Find duplicate rows

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [92]:
df.duplicated().sum()# Count duplicates

0

In [93]:
df[df.duplicated()]# View duplicate rows

Empty DataFrame
Columns: [ai_model_name, query_category, ai_confidence_percentage, response_character_count, has_cited_sources, contains_hedging_words, includes_disclaimer, answer_detail_level, respondent_age_bracket, education_level, digital_literacy_score, ai_familiarity_level, decision_importance, urgency_level, belief_alignment_status, subject_matter_expertise, trust_score_out_of_10, performed_fact_check, fact_check_method_used, verification_duration_mins, answer_accuracy_percentage, trust_calibration_valid, user_skepticism_category]
Index: []

[0 rows x 23 columns]

<h4>Removing duplicates</h4>

<p><b>df.drop_duplicates(inplace=True)</b>-->remove duplicates</p>
<p><b>df.drop_duplicates(subset=['Name'], inplace=True)</b>-->Remove duplicates based on specific columns</p>
<p><b>df.drop_duplicates(keep='last', inplace=True)</b>-->Keep last occurrence</p>

<h4>3️⃣ Checking Inconsistent Data</h4>
<b>What is inconsistent data?</b>
<p>Values that represent same thing but written differently.</p>
<p>eg -->"Male", "male", "M" and "USA", "U.S.A", "United States"</p>

<p>ML treats them as different categories</p>

<h4>Detect inconsistencies</h4>

In [96]:
df.nunique()

ai_model_name                   6
query_category                 12
ai_confidence_percentage      908
response_character_count      541
has_cited_sources               2
contains_hedging_words          2
includes_disclaimer             2
answer_detail_level             4
respondent_age_bracket          6
education_level                 5
digital_literacy_score          4
ai_familiarity_level            5
decision_importance             4
urgency_level                   3
belief_alignment_status         2
subject_matter_expertise        2
trust_score_out_of_10          73
performed_fact_check            2
fact_check_method_used          8
verification_duration_mins    334
answer_accuracy_percentage    896
trust_calibration_valid         2
user_skepticism_category        4
dtype: int64

In [94]:
df['ai_model_name'].unique() # checks unique values

array(['Claude', 'Llama', 'Mistral', 'ChatGPT-3.5', 'Gemini', 'GPT-4'],
      dtype=object)

In [95]:
df['ai_model_name'].value_counts()# Value counts

ai_model_name
Gemini         190
Claude         171
Llama          165
ChatGPT-3.5    160
Mistral        158
GPT-4          156
Name: count, dtype: int64

<h4>Handling Inconsistent Data</h4>
<p><b>df['ai_model_name'] = df['ai_model_name'].str.lower()</b>-->Fix case sensitivity</p>

<p><b>df['ai_model_name'] = df['ai_model_name'].str.strip()</b>-->remove extra spaces</p>

<p><b>df['Gender'].replace({ 'm': 'male'  'f': 'female'}, inplace=True</b>--> replacing value)<p>

<p><b>df['ai_model_name'] = df['ai_model_name'].str.title()</b>-->Standardize text</p>