In [2]:
import pandas as pd

In [26]:
data = pd.read_csv("../ai_skepticism_dataset.csv")
data

,ai_model_name,query_category,ai_confidence_percentage,response_character_count,has_cited_sources,contains_hedging_words,includes_disclaimer,answer_detail_level,respondent_age_bracket,education_level,...,urgency_level,belief_alignment_status,subject_matter_expertise,trust_score_out_of_10,performed_fact_check,fact_check_method_used,verification_duration_mins,answer_accuracy_percentage,trust_calibration_valid,user_skepticism_category
0,Claude,math_calculation,93.23,527,True,False,False,Moderate,45-54,Bachelors,...,Low,False,False,10.0,True,Google Search,10.7,80.15,True,Moderate Trust
1,Llama,recipe_cooking,84.47,581,False,False,False,Specific,55-64,PhD,...,NaN,False,True,7.9,True,Asked Expert,44.3,92.33,True,Skeptical
2,Claude,general_knowledge,69.82,484,True,True,False,Very Specific,35-44,High School,...,NaN,True,False,8.6,True,Consulted Documentation,37.5,67.32,True,Moderate Trust
3,Claude,creative_writing,79.61,73,True,True,False,Specific,45-54,Professional,...,NaN,NaN,False,8.9,True,Checked Official Source,22.7,73.12,True,Moderate Trust
4,Claude,creative_writing,67.71,146,False,True,False,Vague,55-64,Masters,...,NaN,True,True,9.0,True,Academic Paper,43.7,81.05,True,Moderate Trust
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Gemini,math_calculation,94.09,661,True,True,False,Specific,35-44,Masters,...,High,True,True,10.0,False,NaN,0.0,95.33,True,Blind Trust
996,Llama,financial_advice,62.60,384,True,False,False,Vague,65+,Masters,...,High,True,False,8.4,False,NaN,0.0,68.18,True,Blind Trust
997,Claude,technical_coding,77.38,166,True,True,False,Specific,35-44,High School,...,NaN,True,True,10.0,True,Cross-referenced Multiple AIs,23.3,92.14,True,Moderate Trust
998,ChatGPT-3.5,math_calculation,98.61,71,False,True,False,Very Specific,25-34,High School,...,NaN,False,False,8.6,True,Asked Expert,43.3,100.00,True,Moderate Trust
999,Llama,opinion_based,55.61,123,True,True,False,Vague,25-34,PhD,...,Medium,False,True,5.0,True,Personal Testing,44.0,57.10,True,Skeptical

In [27]:
data_type = type(data)
data_type

pandas.core.frame.DataFrame

<h4>Understanding the data</h4>

<h5> 1. Checking no.of rows and columns present in the dataset</h5>

In [30]:
data.shape

(1000, 23)

<h5>2. Checking the Structure of dataset</h5>

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ai_model_name               1000 non-null   object
 1   query_category              1000 non-null   object
 2   ai_confidence_percentage    1000 non-null   float64
 3   response_character_count    1000 non-null   int64
 4   has_cited_sources           1000 non-null   bool
 5   contains_hedging_words      1000 non-null   bool
 6   includes_disclaimer         1000 non-null   bool
 7   answer_detail_level         1000 non-null   object
 8   respondent_age_bracket      1000 non-null   object
 9   education_level             1000 non-null   object
 10  digital_literacy_score      1000 non-null   object
 11  ai_familiarity_level        1000 non-null   object
 12  decision_importance         1000 non-null   object
 13  urgency_level               779 non-null    object
 14  belief_alignment_status     658 non-null    object
 15  subject_matter_expertise    1000 non-null   bool
 16  trust_score_out_of_10       1000 non-null   float64
 17  performed_fact_check        1000 non-null   bool
 18  fact_check_method_used      628 non-null    object
 19  verification_duration_mins  1000 non-null   float64
 20  answer_accuracy_percentage  1000 non-null   float64
 21  trust_calibration_valid     1000 non-null   bool
 22  user_skepticism_category    1000 non-null   object
dtypes: bool(6), float64(4), int64(1), object(12)
memory usage: 138.8+ KB

<h5>3. Checking whether any null values present in the dataset </h5>

In [11]:
df.isnull().sum()  # you can also use any() for checking the null values

ai_model_name                   0
query_category                  0
ai_confidence_percentage        0
response_character_count        0
has_cited_sources               0
contains_hedging_words          0
includes_disclaimer             0
answer_detail_level             0
respondent_age_bracket          0
education_level                 0
digital_literacy_score          0
ai_familiarity_level            0
decision_importance             0
urgency_level                 221
belief_alignment_status       342
subject_matter_expertise        0
trust_score_out_of_10           0
performed_fact_check            0
fact_check_method_used        372
verification_duration_mins      0
answer_accuracy_percentage      0
trust_calibration_valid         0
user_skepticism_category        0
dtype: int64

<h5>4. Handling the missing values</h5>

In [35]:
data['urgency_level'].fillna("Unknown")
data['belief_alignment_status'].fillna("Unknown")
data['fact_check_method_used'].fillna("Unknown")

<h5>5. Checking Duplicates</h5>
<h6>If any duplicates exist use drop_duplicates()</h6>

In [41]:
data.duplicated().sum()

0

<h5>6. Checking the unique values</h5>

In [53]:
data['ai_model_name'].unique()
data["query_category"].unique()
data["education_level"].unique()

array(['claude', 'llama', 'mistral', 'chatgpt-3.5', 'gemini', 'gpt-4'],
      dtype=object)

<h5>7. Fixing the values</h5>

In [54]:
data['ai_model_name'] = data['ai_model_name'].str.upper().str.strip()
data['ai_model_name']

0           CLAUDE
1            LLAMA
2           CLAUDE
3           CLAUDE
4           CLAUDE
          ...
995         GEMINI
996          LLAMA
997         CLAUDE
998    CHATGPT-3.5
999          LLAMA
Name: ai_model_name, Length: 1000, dtype: object

<h5>8. Checking the Outliers</h5>

In [55]:
df.describe()

,ai_confidence_percentage,response_character_count,trust_score_out_of_10,verification_duration_mins,answer_accuracy_percentage
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,72.006790,429.022000,7.905000,14.840000,69.982020
std,14.663334,221.644937,1.766866,15.182336,18.176782
min,40.520000,50.000000,1.800000,0.000000,19.420000
25%,60.570000,239.500000,6.700000,0.000000,58.570000
50%,74.235000,423.000000,8.200000,11.050000,72.080000
75%,83.862500,629.000000,9.500000,28.200000,83.140000
max,98.660000,799.000000,10.000000,45.000000,100.000000